version: "3.8"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_inspector_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment: 
      - DB_URL=mysql+pymysql://root:root@database:3306/code_inspector_db
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/app
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
